apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnext
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnext
  template:
    metadata:
      labels:
        app: vnext
    spec:
      containers:
      - image: okteto/vnext
        name: vnext

---

apiVersion: v1
kind: Service
metadata:
  name: vnext
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "vnext"
    port: 8080
  selector:
    app: vnext
